global:
  webapp:
    name: webapp
    deployment: webapp
    port: 80
    url: webapp.local
    service: webapp-service
    hpa: web-hpa
    account: sa-webapp

  applicantsapi:
    name: applicants-api
    deployment: applicants-api
    port: 80
    service: applicants-api

  apijobs:
    name: service-api-jobs
    deployment: service-api-jobs
    port: 80
    service: service-api-jobs
  
  apiidentity:
    name: service-api-identity
    deployment: service-api-identity
    port: 80
    service: service-api-identity

  userdata:
    name: user-data
    deployment: user-data
    port: 6379
    service: user-data 
    pvc: user-data-pvc

  rabbitmq:
    name: rabbitmq
    deployment: rabbitmq
    port1: 5672
    port2: 15672
    service: rabbitmq

  ingress:
    namespace: projet-conteneurisation-ingress-nginx
    webapp: 
      name: webapp-ingress

    logging:
      name: kibana
      namespace: projet-conteneurisation-logging
      host:
       name: kibana
       service: kibana
       port: 5601

    monitoring:
      name: monitoring-ingress
      namespace: projet-conteneurisation-monitoring
      config: prometheus-config
      host1: 
        name: prometheus
        service: prometheus-service
        port: 80
      host2: 
        name: grafana 
        service: grafana
        port: 80

  prometheus:
    name: prometheus
    deployment: prometheus-server
    service: prometheus-service
    port1: 80
    port2: 9090
    account: prometheus-sa
    config: prometheus-rules

  elasticsearch:
    name: elasticsearch
    deployment: elasticsearch
    service: elasticsearch
    port: 9200

  kibana:
    name: kibana
    deployment: kibana
    service: kibana
    port: 5601
  
  sqldata:
    name: sql-data
    deployment: sql-data
    port: 1433
    pvc: sql-data-pvc
    service: sql-data

  security:
    networkpolicy: 
      name: allow-api-to-sql
      port: 5432
      type: Ingress
    prometheus:
      rbac:
        metrics: prometheus-system-metrics
        binding: prometheus-system-metrics-binding
    fluentd:
      rbac:
        account: fluentd
    rbac:
      reader: role-webapp-lecteur
      binding: bind-webapp-role
 
  sslcert: #Base 64
    name: web-tls
