apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ .Values.global.security.prometheus.rbac.metrics }}
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: 
  - "/metrics"
  - "/metrics/cadvisor"
  - "/metrics/probes"
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ .Values.global.security.prometheus.rbac.binding }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.prometheus.name }}
  namespace:  {{ .Values.global.ingress.monitoring.namespace }}
roleRef:
  kind: ClusterRole
  name:  {{ .Values.global.security.prometheus.rbac.metrics }}
  apiGroup: rbac.authorization.k8s.io