apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.elasticsearch.deployment }}
  namespace: {{ .Values.global.ingress.logging.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.elasticsearch.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.elasticsearch.name }}
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        env:
        - name: discovery.type
          value: single-node
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        ports:
        - containerPort: {{ .Values.global.elasticsearch.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.elasticsearch.service }}
  namespace: {{ .Values.global.ingress.logging.namespace }}
spec:
  selector:
    app: {{ .Values.global.elasticsearch.name }}
  ports:
    - port: {{ .Values.global.elasticsearch.port }}
      targetPort: {{ .Values.global.elasticsearch.port }}